version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run Build
          command: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python test.py

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: Deployment Placeholder
          command: echo "Deployment Done"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
